#!/bin/bash
#
# Kiosk player loop:
#   - shows splash while the stream is idle
#   - starts mpv when the stream goes live
#   - returns to splash when the stream ends / mpv exits
#
# Generated by setup-kiosk.sh on 20260418-182637

set -u

LOG=/tmp/player.log
exec >> "$LOG" 2>&1

STREAM_URL="rtmp://127.0.0.1/live/church242"
SPLASH_IMAGE="/home/kiosk/splash.png"
VOLUME=80

show_splash() {
    mpv --fullscreen --really-quiet --loop \
        --image-display-duration=inf \
        --no-input-default-bindings \
        --no-audio \
        "$SPLASH_IMAGE" &
    echo $!
}

stream_live() {
    timeout 10 ffprobe \
        -v quiet \
        -show_entries stream=codec_type \
        -of default=nw=1:nk=1 \
        "$STREAM_URL" 2>/dev/null | grep -q .
}

while true; do
    echo "[$(date)] loop top"
    # Wait for nginx RTMP port to be ready
    until nc -z 127.0.0.1 1935 2>/dev/null; do
        echo "[$(date)] waiting for nginx..."
        sleep 2
    done
    echo "[$(date)] nginx ready"
    if ! stream_live; then
       echo "[$(date)] stream not live, showing splash"
       SPLASH_PID=$(show_splash)
        while ! stream_live; do
	    echo "[$(date)] still waiting for stream..."
            sleep 3
        done
	echo "[$(date)] stream detected, killing splash $SPLASH_PID"
        kill "$SPLASH_PID" 2>/dev/null || true
        wait "$SPLASH_PID" 2>/dev/null || true
    fi

    echo "[$(date)] launching mpv"
    mpv --fullscreen \
        --hwdec=auto-safe \
        --cache=yes --demuxer-max-bytes=8MiB \
        --demuxer-readahead-secs=5 \
        --audio-device=auto \
        --volume="$VOLUME" \
        --no-correct-pts \
        --hr-seek=no \
	--stream-lavf-o=fflags=+genpts+igndts+discardcorrupt \
	--stream-lavf-o=ts_delta_threshold=9000 \
	--stream-lavf-o=max_ts_probe=3 \
        --no-osc --no-osd-bar \
        --no-input-default-bindings \
        --really-quiet \
        --msg-level=all=warn \
        "$STREAM_URL" || true
        # --stream-lavf-o=fflags=+genpts+igndts+discardcorrupt \
        # --stream-lavf-o=analyzeduration=5000000 \

    echo "[$(date)] mpv exited: $?"
    sleep 2
done
