#!/bin/bash
#
# kiosk-web-tls-setup.sh — Put the volunteer web manager behind HTTPS with a
# Let's Encrypt certificate obtained via the DNS-01 challenge.
#
# DNS-01 is used (not HTTP-01) so the Pi never needs to be reachable from the
# public internet — you only need control of the domain's DNS. With a certbot
# DNS plugin the cert also auto-renews unattended.
#
# What it does:
#   1. Obtains a cert for $DOMAIN via `certbot certonly` (DNS-01).
#   2. Writes /etc/nginx/kiosk-web-site.d/site.conf as an HTTPS server block
#      (with an HTTP->HTTPS redirect and HSTS), replacing the HTTP-only block.
#   3. Sets PUBLIC_URL=https://$DOMAIN in /etc/kiosk-web.conf so the manager's
#      shareable links and downloadable shortcuts use the canonical HTTPS URL.
#   4. Installs a renewal deploy-hook that reloads nginx after each renewal.
#   5. `nginx -t` and reloads nginx; restarts kiosk-web.
#
# Usage:
#   sudo DOMAIN=kiosk.church.org EMAIL=av@church.org \
#        CERTBOT_ARGS="--dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini" \
#        bash install/kiosk-web-tls-setup.sh
#
#   CERTBOT_ARGS holds your DNS provider's certbot plugin flags. If omitted,
#   the script falls back to the interactive --manual DNS challenge, which
#   CANNOT auto-renew — you would have to re-run this every ~90 days. Using a
#   provider plugin is strongly recommended for a set-and-forget kiosk.
#
# Re-running is safe and idempotent.

set -euo pipefail

DOMAIN="${DOMAIN:-}"
EMAIL="${EMAIL:-}"
CERTBOT_ARGS="${CERTBOT_ARGS:-}"
CONF="/etc/kiosk-web.conf"
SITE_DIR="/etc/nginx/kiosk-web-site.d"
SITE_FILE="$SITE_DIR/site.conf"
HOOK_DIR="/etc/letsencrypt/renewal-hooks/deploy"

log() { printf '\033[1;34m[kiosk-web-tls]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[kiosk-web-tls] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Must run as root: sudo DOMAIN=... bash $0"
[[ -n "$DOMAIN" ]] || die "Set DOMAIN=your.domain (the name the cert is for)."
command -v certbot >/dev/null 2>&1 || die "certbot not installed. Try: apt-get install certbot (plus your DNS plugin, e.g. python3-certbot-dns-cloudflare)."
command -v nginx   >/dev/null 2>&1 || die "nginx not installed."

# 1. Obtain the certificate via DNS-01.
if [[ -n "$CERTBOT_ARGS" ]]; then
    log "Requesting cert for $DOMAIN via certbot DNS plugin (auto-renewable)..."
    EMAIL_ARG=(--register-unsafely-without-email)
    [[ -n "$EMAIL" ]] && EMAIL_ARG=(-m "$EMAIL")
    # shellcheck disable=SC2086
    certbot certonly --non-interactive --agree-tos "${EMAIL_ARG[@]}" \
        --preferred-challenges dns $CERTBOT_ARGS -d "$DOMAIN"
else
    log "No CERTBOT_ARGS given — falling back to the interactive --manual DNS challenge."
    log "NOTE: manual certs do NOT auto-renew; you must re-run this before expiry (~90 days)."
    EMAIL_ARG=(--register-unsafely-without-email)
    [[ -n "$EMAIL" ]] && EMAIL_ARG=(-m "$EMAIL")
    certbot certonly --manual --preferred-challenges dns --agree-tos \
        "${EMAIL_ARG[@]}" -d "$DOMAIN"
fi

LIVE="/etc/letsencrypt/live/$DOMAIN"
[[ -f "$LIVE/fullchain.pem" ]] || die "Cert not found at $LIVE — certbot did not complete."

# 2. Write the HTTPS site block (replaces the HTTP-only one).
log "Writing HTTPS nginx site block to $SITE_FILE..."
mkdir -p "$SITE_DIR"
cat > "$SITE_FILE" <<NGINX
# Volunteer web manager — HTTPS. Generated by kiosk-web-tls-setup.sh for
# $DOMAIN. Do not hand-edit; re-run the script to regenerate.
server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name $DOMAIN;
    client_max_body_size 15M;
    access_log /var/log/nginx/access.log kiosk_redacted;

    ssl_certificate     $LIVE/fullchain.pem;
    ssl_certificate_key $LIVE/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        proxy_pass         http://127.0.0.1:5000;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }
}
NGINX
chmod 0644 "$SITE_FILE"

# 3. Set PUBLIC_URL so shareable links / shortcut files use the canonical HTTPS
#    domain rather than whatever Host header the admin's browser happened to send.
PUBLIC_URL="https://$DOMAIN"
if grep -q '^PUBLIC_URL=' "$CONF" 2>/dev/null; then
    sed -i "s#^PUBLIC_URL=.*#PUBLIC_URL=$PUBLIC_URL#" "$CONF"
    log "Updated PUBLIC_URL in $CONF."
else
    echo "PUBLIC_URL=$PUBLIC_URL" >> "$CONF"
    log "Added PUBLIC_URL to $CONF."
fi

# 4. Install a renewal deploy-hook so nginx picks up renewed certs.
mkdir -p "$HOOK_DIR"
cat > "$HOOK_DIR/reload-nginx.sh" <<'HOOK'
#!/bin/bash
# Reload nginx after a Let's Encrypt renewal so it serves the new cert.
systemctl reload nginx
HOOK
chmod 0755 "$HOOK_DIR/reload-nginx.sh"

# 5. Validate and reload.
log "Validating nginx config..."
nginx -t || die "nginx -t failed — the HTTPS site block was written but nginx was NOT reloaded. Fix the error above, then: systemctl reload nginx"
systemctl reload nginx
systemctl restart kiosk-web

log ""
log "HTTPS is live: $PUBLIC_URL"
log "Open the manager, then use the Access Link card to copy the link or"
log "download a fresh .webloc/.url shortcut for volunteers."
