#!/bin/bash
#
# kiosk-web-tls-local.sh — Serve the volunteer web manager over HTTPS using a
# locally-signed certificate. No domain, no DNS, no internet — everything is
# generated on the Pi. This is the DEFAULT HTTPS path (kiosk-web-setup.sh calls
# it); kiosk-web-tls-setup.sh is the alternative for a publicly-trusted
# Let's Encrypt cert when you have a domain.
#
# How it works:
#   1. Generates a per-Pi root CA (once) and a server cert signed by it, with
#      the hostname, <hostname>.local, and every LAN IP as Subject Alt Names.
#   2. Writes an nginx site block: :443 serves the manager over TLS with HSTS;
#      :80 serves the root CA at /rootCA.crt (so a fresh device can fetch and
#      trust it) and 301-redirects everything else to HTTPS.
#   3. Sets PUBLIC_URL=https://<hostname> so shareable links use HTTPS.
#
# One-time per device: import the root CA (download http://<pi>/rootCA.crt) so
# the browser shows a real padlock with no warning. Until a device trusts the
# CA it gets the usual "not trusted" prompt (HSTS is only ever seen by devices
# that already trust the CA, so it can't lock anyone out).
#
# The root CA is stable across runs (so trust you've installed keeps working);
# the server cert is regenerated each run, which picks up a changed hostname or
# DHCP address. Run again after the Pi's IP changes.
#
# Usage:
#   sudo bash install/kiosk-web-tls-local.sh
#   sudo PUBLIC_HOST=displaypi.local bash install/kiosk-web-tls-local.sh   # override the link host
#
# Re-running is safe and idempotent.

set -euo pipefail

CONF="/etc/kiosk-web.conf"
SITE_DIR="/etc/nginx/kiosk-web-site.d"
SITE_FILE="$SITE_DIR/site.conf"
TLS_DIR="/etc/kiosk-web/tls"
CA_DIR="/etc/kiosk-web/ca"
CA_KEY="$CA_DIR/rootCA.key"
CA_CRT="$CA_DIR/rootCA.crt"
SRV_KEY="$TLS_DIR/server.key"
SRV_CRT="$TLS_DIR/server.crt"
CA_DAYS=3650
SRV_DAYS=3650

log() { printf '\033[1;34m[kiosk-web-tls-local]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[kiosk-web-tls-local] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Must run as root: sudo bash $0"
command -v openssl >/dev/null 2>&1 || die "openssl not installed."
command -v nginx   >/dev/null 2>&1 || die "nginx not installed."

HOSTNAME_FULL="$(hostname)"
PUBLIC_HOST="${PUBLIC_HOST:-$HOSTNAME_FULL}"

mkdir -p "$CA_DIR" "$TLS_DIR"
chmod 0755 "$CA_DIR" "$TLS_DIR"

# 1. Root CA — generated once and then reused, so trust installed on devices
#    keeps working across re-runs.
if [[ -f "$CA_KEY" && -f "$CA_CRT" ]]; then
    log "Reusing existing root CA at $CA_CRT."
else
    log "Generating a per-Pi root CA..."
    openssl genrsa -out "$CA_KEY" 4096 2>/dev/null
    openssl req -x509 -new -nodes -key "$CA_KEY" -sha256 -days "$CA_DAYS" \
        -subj "/O=display-pi/CN=display-pi Local CA ($HOSTNAME_FULL)" \
        -out "$CA_CRT" 2>/dev/null
fi
chmod 0600 "$CA_KEY"
chmod 0644 "$CA_CRT"   # public — served over HTTP for devices to import

# 2. Server certificate — regenerated each run so a changed hostname or DHCP
#    address is reflected in the Subject Alt Names.
log "Signing a server certificate for $HOSTNAME_FULL and its LAN addresses..."
sans="DNS:$HOSTNAME_FULL, DNS:$HOSTNAME_FULL.local, DNS:localhost, IP:127.0.0.1"
for ip in $(hostname -I 2>/dev/null); do
    sans="$sans, IP:$ip"
done

openssl genrsa -out "$SRV_KEY" 2048 2>/dev/null
csr="$(mktemp)"; ext="$(mktemp)"
trap 'rm -f "$csr" "$ext"' EXIT
openssl req -new -key "$SRV_KEY" -subj "/CN=$HOSTNAME_FULL" -out "$csr" 2>/dev/null
printf 'basicConstraints = CA:FALSE\nextendedKeyUsage = serverAuth\nsubjectAltName = %s\n' \
    "$sans" > "$ext"
openssl x509 -req -in "$csr" -CA "$CA_CRT" -CAkey "$CA_KEY" -CAcreateserial \
    -out "$SRV_CRT" -days "$SRV_DAYS" -sha256 -extfile "$ext" 2>/dev/null
chmod 0600 "$SRV_KEY"
chmod 0644 "$SRV_CRT"

openssl verify -CAfile "$CA_CRT" "$SRV_CRT" >/dev/null 2>&1 \
    || die "Generated server cert does not verify against the CA."

# 3. nginx site block: HTTPS + HSTS, with the CA fetchable over HTTP.
log "Writing HTTPS nginx site block to $SITE_FILE..."
mkdir -p "$SITE_DIR"
cat > "$SITE_FILE" <<NGINX
# Volunteer web manager — HTTPS with a locally-signed cert. Generated by
# kiosk-web-tls-local.sh. Do not hand-edit; re-run the script to regenerate.
server {
    listen 80;
    server_name _;

    # Let a fresh device fetch the root CA over plain HTTP to import it once;
    # force everything else to HTTPS.
    location = /rootCA.crt {
        alias $CA_CRT;
        default_type application/x-x509-ca-cert;
        add_header Content-Disposition 'attachment; filename="display-pi-rootCA.crt"';
    }
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name _;
    client_max_body_size 15M;
    access_log /var/log/nginx/access.log kiosk_redacted;

    ssl_certificate     $SRV_CRT;
    ssl_certificate_key $SRV_KEY;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    # Safe here: only devices that already trust the CA ever complete the TLS
    # handshake and see this header, so HSTS can't lock out an un-trusting one.
    add_header Strict-Transport-Security "max-age=31536000" always;

    location = /rootCA.crt {
        alias $CA_CRT;
        default_type application/x-x509-ca-cert;
        add_header Content-Disposition 'attachment; filename="display-pi-rootCA.crt"';
    }
    location / {
        proxy_pass         http://127.0.0.1:5000;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }
}
NGINX
chmod 0644 "$SITE_FILE"

# 4. Canonical HTTPS base for shareable links / shortcut files.
PUBLIC_URL="https://$PUBLIC_HOST"
if [[ -f "$CONF" ]] && grep -q '^PUBLIC_URL=' "$CONF"; then
    sed -i "s#^PUBLIC_URL=.*#PUBLIC_URL=$PUBLIC_URL#" "$CONF"
    log "Updated PUBLIC_URL in $CONF."
else
    echo "PUBLIC_URL=$PUBLIC_URL" >> "$CONF"
    log "Added PUBLIC_URL to $CONF."
fi

# 5. Validate and reload.
log "Validating nginx config..."
nginx -t || die "nginx -t failed — the site block was written but nginx was NOT reloaded. Fix the error above, then: systemctl reload nginx"
systemctl reload nginx
systemctl restart kiosk-web 2>/dev/null || true

PRIMARY_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
log ""
log "HTTPS is live: $PUBLIC_URL"
log ""
log "One-time per device — trust this Pi's CA for a warning-free padlock:"
log "  1. Download  http://${PRIMARY_IP:-$HOSTNAME_FULL}/rootCA.crt"
log "     (also at   $CA_CRT on the Pi)"
log "  2. Import it as a trusted root/authority on the device."
log "Until a device trusts the CA it will show a certificate warning."
